# copy the os.html from master to appropriate nodes with their names
# scp 
---
- name: Config Apache Web Server
  hosts: all
  become: yes
  vars:
    user_name: Sai
    custom_http_port: 8090
  
  tasks:
  - name: copy config to Amazon httpd
    template:
      src: httpd.j2
      dest: /etc/httpd/conf/httpd.conf
    when: ansible_distribution  == "Amazon"

  - name: Set Permissive For HTTPD
    selinux:
      policy: targeted
      state: permissive
    when: ansible_distribution  == "Amazon"     

  - name: Restart HTTPD
    service:
      name: httpd
      state: restarted
    when: ansible_distribution  == "Amazon"

  - name: copy config to Ubuntu apache2
    template:
      src: ports.j2
      dest: /etc/apache2/ports.conf
    when: ansible_distribution  == "Ubuntu"
  
  - name: Restart APACHE2
    service:
      name: apache2
      state: restarted
    when: ansible_distribution  == "Ubuntu"
...        
