# "ansible_distribution": "Amazon"
# "ansible_distribution": "Ubuntu"
# "ansible_distribution": "Amazon"

---
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution  == "Amazon" or ansible_distribution == "Amazon"
  
  - name: install GIT
    yum:
      name: git
      state: present
    when: ansible_distribution  == "Amazon" or ansible_distribution == "Amazon"

  - name: start httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution  == "Amazon" or ansible_distribution == "Amazon"
  
  - name: enable httpd
    service:
      name: httpd
      enabled: true
    when: ansible_distribution  == "Amazon" or ansible_distribution == "Amazon"    

  - name: install Apache2
    apt:
      name: apache2
      state: present
    when: ansible_distribution  == "Ubuntu" or ansible_distribution == "Ubuntu"
 
  - name: start apache2
    service:
      name: apache2
      state: started
    when: ansible_distribution  == "Ubuntu" or ansible_distribution == "Ubuntu"

  - name: enable apache2
    service:
      name: apache2
      enabled: true
    when: ansible_distribution  == "Ubuntu" or ansible_distribution == "Ubuntu"
...        
